{% set name = "libpressio" %}
{% set version = "0.94.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/robertu94/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4250597cdd54043a7d5009ffc3feea3eac9496cdd38ea3f61f9727b7acd09add

build:
  skip: True  # [win or osx]
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - python
    - pybind11
    - sz
    - sz3
    - swig
    - fpzip
    - lua
    - numpy
    - hdf5
    - stdcompat
    - openmpi=4.1.4
    - mpi4py
    - sol2
    - nlohmann_json
    - qoz
  run:
    - python
    - sz
    - sz3
    - swig
    - fpzip
    - lua
    - numpy
    - hdf5
    - stdcompat
    - numcodecs
    - openmpi=4.1.4
    - mpi4py
    - sol2
    - nlohmann_json
    - qoz
about:
  home: https://robertu94.github.io/libpressio
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT.txt
  summary: 'Library to abstract between compressors and their configurations'
  description: |
    pressio is latin for compression. LibPressio is a C++ library with
    C compatible bindings to abstract between different lossless and
    lossy compressors and their configurations. It solves the problem
    of having to having to write separate application level code for
    each lossy compressor that is developed. Instead, users write
    application level code using LibPressio, and the library will make
    the correct underlying calls to the compressors. It provides
    interfaces to represent data, compressors settings, and compressors.
  doc_url: https://robertu94.github.io/libpressio
  dev_url: https://github.com/robertu94/libpressio

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
